# Generated by Django 4.2.7 on 2023-12-28 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("date_time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "type_of_visit",
                    models.CharField(
                        choices=[("INIT", "Initial"), ("REPT", "Repeat")],
                        default="REPT",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "ordering": ("date_time",),
            },
        ),
    ]
